2021-09-22 19:18:22,225 - root - ERROR - ('140228', 'not_found')
2021-09-22 19:18:22,226 - root - ERROR - list index out of range
2021-09-22 19:18:22,228 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:20:57,637 - root - ERROR - ('142249', 'not_found')
2021-09-22 19:20:57,638 - root - ERROR - list index out of range
2021-09-22 19:20:57,638 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:24:49,678 - root - ERROR - ('230819', 'not_found')
2021-09-22 19:24:49,678 - root - ERROR - list index out of range
2021-09-22 19:24:49,678 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:26:52,808 - root - ERROR - ('320219', 'not_found')
2021-09-22 19:26:52,808 - root - ERROR - list index out of range
2021-09-22 19:26:52,808 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:27:38,804 - root - ERROR - ('320819', 'not_found')
2021-09-22 19:27:38,804 - root - ERROR - list index out of range
2021-09-22 19:27:38,805 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:28:51,545 - root - ERROR - ('330128', 'not_found')
2021-09-22 19:28:51,545 - root - ERROR - list index out of range
2021-09-22 19:28:51,545 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:29:05,575 - root - ERROR - ('330419', 'not_found')
2021-09-22 19:29:05,575 - root - ERROR - list index out of range
2021-09-22 19:29:05,575 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:32:07,335 - root - ERROR - ('342603', 'not_found')
2021-09-22 19:32:07,335 - root - ERROR - list index out of range
2021-09-22 19:32:07,335 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:32:52,393 - root - ERROR - ('350221', 'not_found')
2021-09-22 19:32:52,393 - root - ERROR - list index out of range
2021-09-22 19:32:52,393 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:32:53,213 - root - ERROR - ('350304', 'not_found')
2021-09-22 19:32:53,213 - root - ERROR - list index out of range
2021-09-22 19:32:53,214 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:32:56,186 - root - ERROR - ('350420', 'not_found')
2021-09-22 19:32:56,186 - root - ERROR - list index out of range
2021-09-22 19:32:56,186 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:32:57,311 - root - ERROR - ('350505', 'not_found')
2021-09-22 19:32:57,311 - root - ERROR - list index out of range
2021-09-22 19:32:57,311 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:32:58,126 - root - ERROR - ('350522', 'not_found')
2021-09-22 19:32:58,126 - root - ERROR - list index out of range
2021-09-22 19:32:58,126 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:32:58,946 - root - ERROR - ('350523', 'not_found')
2021-09-22 19:32:58,946 - root - ERROR - list index out of range
2021-09-22 19:32:58,946 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:00,072 - root - ERROR - ('350621', 'not_found')
2021-09-22 19:33:00,072 - root - ERROR - list index out of range
2021-09-22 19:33:00,072 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:01,204 - root - ERROR - ('350902', 'not_found')
2021-09-22 19:33:01,205 - root - ERROR - list index out of range
2021-09-22 19:33:01,205 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:02,324 - root - ERROR - ('350921', 'not_found')
2021-09-22 19:33:02,324 - root - ERROR - list index out of range
2021-09-22 19:33:02,324 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:03,453 - root - ERROR - ('350922', 'not_found')
2021-09-22 19:33:03,453 - root - ERROR - list index out of range
2021-09-22 19:33:03,453 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:04,580 - root - ERROR - ('350923', 'not_found')
2021-09-22 19:33:04,581 - root - ERROR - list index out of range
2021-09-22 19:33:04,581 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:05,704 - root - ERROR - ('350924', 'not_found')
2021-09-22 19:33:05,704 - root - ERROR - list index out of range
2021-09-22 19:33:05,704 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:06,524 - root - ERROR - ('350926', 'not_found')
2021-09-22 19:33:06,524 - root - ERROR - list index out of range
2021-09-22 19:33:06,524 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:07,650 - root - ERROR - ('350981', 'not_found')
2021-09-22 19:33:07,650 - root - ERROR - list index out of range
2021-09-22 19:33:07,650 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:08,374 - root - ERROR - ('350982', 'not_found')
2021-09-22 19:33:08,374 - root - ERROR - list index out of range
2021-09-22 19:33:08,374 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:09,189 - root - ERROR - ('352101', 'not_found')
2021-09-22 19:33:09,189 - root - ERROR - list index out of range
2021-09-22 19:33:09,190 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:10,005 - root - ERROR - ('352102', 'not_found')
2021-09-22 19:33:10,005 - root - ERROR - list index out of range
2021-09-22 19:33:10,005 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:10,721 - root - ERROR - ('352103', 'not_found')
2021-09-22 19:33:10,721 - root - ERROR - list index out of range
2021-09-22 19:33:10,721 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:11,778 - root - ERROR - ('352104', 'not_found')
2021-09-22 19:33:11,778 - root - ERROR - list index out of range
2021-09-22 19:33:11,779 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:12,872 - root - ERROR - ('352121', 'not_found')
2021-09-22 19:33:12,872 - root - ERROR - list index out of range
2021-09-22 19:33:12,872 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:13,592 - root - ERROR - ('352122', 'not_found')
2021-09-22 19:33:13,592 - root - ERROR - list index out of range
2021-09-22 19:33:13,592 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:14,306 - root - ERROR - ('352123', 'not_found')
2021-09-22 19:33:14,306 - root - ERROR - list index out of range
2021-09-22 19:33:14,307 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:15,435 - root - ERROR - ('352124', 'not_found')
2021-09-22 19:33:15,435 - root - ERROR - list index out of range
2021-09-22 19:33:15,435 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:16,559 - root - ERROR - ('352127', 'not_found')
2021-09-22 19:33:16,559 - root - ERROR - list index out of range
2021-09-22 19:33:16,559 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:17,600 - root - ERROR - ('352128', 'not_found')
2021-09-22 19:33:17,601 - root - ERROR - list index out of range
2021-09-22 19:33:17,601 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:18,632 - root - ERROR - ('352129', 'not_found')
2021-09-22 19:33:18,632 - root - ERROR - list index out of range
2021-09-22 19:33:18,632 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:19,584 - root - ERROR - ('352221', 'not_found')
2021-09-22 19:33:19,584 - root - ERROR - list index out of range
2021-09-22 19:33:19,584 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:20,349 - root - ERROR - ('352224', 'not_found')
2021-09-22 19:33:20,349 - root - ERROR - list index out of range
2021-09-22 19:33:20,349 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:21,474 - root - ERROR - ('352226', 'not_found')
2021-09-22 19:33:21,474 - root - ERROR - list index out of range
2021-09-22 19:33:21,474 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:22,600 - root - ERROR - ('352524', 'not_found')
2021-09-22 19:33:22,600 - root - ERROR - list index out of range
2021-09-22 19:33:22,600 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:23,317 - root - ERROR - ('352601', 'not_found')
2021-09-22 19:33:23,317 - root - ERROR - list index out of range
2021-09-22 19:33:23,317 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:24,138 - root - ERROR - ('352602', 'not_found')
2021-09-22 19:33:24,139 - root - ERROR - list index out of range
2021-09-22 19:33:24,139 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:25,263 - root - ERROR - ('352622', 'not_found')
2021-09-22 19:33:25,263 - root - ERROR - list index out of range
2021-09-22 19:33:25,263 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:25,981 - root - ERROR - ('352623', 'not_found')
2021-09-22 19:33:25,982 - root - ERROR - list index out of range
2021-09-22 19:33:25,982 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:26,696 - root - ERROR - ('352624', 'not_found')
2021-09-22 19:33:26,696 - root - ERROR - list index out of range
2021-09-22 19:33:26,696 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:27,829 - root - ERROR - ('352625', 'not_found')
2021-09-22 19:33:27,829 - root - ERROR - list index out of range
2021-09-22 19:33:27,830 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:28,643 - root - ERROR - ('352626', 'not_found')
2021-09-22 19:33:28,643 - root - ERROR - list index out of range
2021-09-22 19:33:28,644 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:29,461 - root - ERROR - ('352627', 'not_found')
2021-09-22 19:33:29,461 - root - ERROR - list index out of range
2021-09-22 19:33:29,461 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:30,281 - root - ERROR - ('359001', 'not_found')
2021-09-22 19:33:30,281 - root - ERROR - list index out of range
2021-09-22 19:33:30,281 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:30,998 - root - ERROR - ('359002', 'not_found')
2021-09-22 19:33:30,999 - root - ERROR - list index out of range
2021-09-22 19:33:30,999 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:31,805 - root - ERROR - ('360211', 'not_found')
2021-09-22 19:33:31,805 - root - ERROR - list index out of range
2021-09-22 19:33:31,806 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:37,714 - root - ERROR - ('360212', 'not_found')
2021-09-22 19:33:37,714 - root - ERROR - list index out of range
2021-09-22 19:33:37,714 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:38,779 - root - ERROR - ('360221', 'not_found')
2021-09-22 19:33:38,779 - root - ERROR - list index out of range
2021-09-22 19:33:38,779 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:39,498 - root - ERROR - ('360311', 'not_found')
2021-09-22 19:33:39,498 - root - ERROR - list index out of range
2021-09-22 19:33:39,498 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:40,626 - root - ERROR - ('360312', 'not_found')
2021-09-22 19:33:40,626 - root - ERROR - list index out of range
2021-09-22 19:33:40,626 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:41,341 - root - ERROR - ('360422', 'not_found')
2021-09-22 19:33:41,341 - root - ERROR - list index out of range
2021-09-22 19:33:41,341 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:42,465 - root - ERROR - ('360621', 'not_found')
2021-09-22 19:33:42,465 - root - ERROR - list index out of range
2021-09-22 19:33:42,465 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:43,595 - root - ERROR - ('360802', 'not_found')
2021-09-22 19:33:43,595 - root - ERROR - list index out of range
2021-09-22 19:33:43,595 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:44,315 - root - ERROR - ('360822', 'not_found')
2021-09-22 19:33:44,315 - root - ERROR - list index out of range
2021-09-22 19:33:44,315 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:45,341 - root - ERROR - ('360823', 'not_found')
2021-09-22 19:33:45,341 - root - ERROR - list index out of range
2021-09-22 19:33:45,341 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:46,460 - root - ERROR - ('360826', 'not_found')
2021-09-22 19:33:46,460 - root - ERROR - list index out of range
2021-09-22 19:33:46,460 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:47,588 - root - ERROR - ('360828', 'not_found')
2021-09-22 19:33:47,588 - root - ERROR - list index out of range
2021-09-22 19:33:47,589 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:48,305 - root - ERROR - ('360830', 'not_found')
2021-09-22 19:33:48,305 - root - ERROR - list index out of range
2021-09-22 19:33:48,306 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:49,123 - root - ERROR - ('360902', 'not_found')
2021-09-22 19:33:49,123 - root - ERROR - list index out of range
2021-09-22 19:33:49,123 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:50,152 - root - ERROR - ('360922', 'not_found')
2021-09-22 19:33:50,152 - root - ERROR - list index out of range
2021-09-22 19:33:50,152 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:51,275 - root - ERROR - ('360923', 'not_found')
2021-09-22 19:33:51,275 - root - ERROR - list index out of range
2021-09-22 19:33:51,275 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:52,028 - root - ERROR - ('360981', 'not_found')
2021-09-22 19:33:52,029 - root - ERROR - list index out of range
2021-09-22 19:33:52,029 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:52,824 - root - ERROR - ('360982', 'not_found')
2021-09-22 19:33:52,824 - root - ERROR - list index out of range
2021-09-22 19:33:52,825 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:53,938 - root - ERROR - ('360983', 'not_found')
2021-09-22 19:33:53,938 - root - ERROR - list index out of range
2021-09-22 19:33:53,938 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:54,682 - root - ERROR - ('361021', 'not_found')
2021-09-22 19:33:54,682 - root - ERROR - list index out of range
2021-09-22 19:33:54,682 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:55,369 - root - ERROR - ('361023', 'not_found')
2021-09-22 19:33:55,369 - root - ERROR - list index out of range
2021-09-22 19:33:55,369 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:56,193 - root - ERROR - ('361121', 'not_found')
2021-09-22 19:33:56,193 - root - ERROR - list index out of range
2021-09-22 19:33:56,193 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:57,314 - root - ERROR - ('361124', 'not_found')
2021-09-22 19:33:57,314 - root - ERROR - list index out of range
2021-09-22 19:33:57,314 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:58,388 - root - ERROR - ('361127', 'not_found')
2021-09-22 19:33:58,388 - root - ERROR - list index out of range
2021-09-22 19:33:58,388 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:33:59,159 - root - ERROR - ('361129', 'not_found')
2021-09-22 19:33:59,160 - root - ERROR - list index out of range
2021-09-22 19:33:59,160 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:00,284 - root - ERROR - ('362001', 'not_found')
2021-09-22 19:34:00,284 - root - ERROR - list index out of range
2021-09-22 19:34:00,284 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:01,413 - root - ERROR - ('362101', 'not_found')
2021-09-22 19:34:01,413 - root - ERROR - list index out of range
2021-09-22 19:34:01,413 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:02,539 - root - ERROR - ('362102', 'not_found')
2021-09-22 19:34:02,539 - root - ERROR - list index out of range
2021-09-22 19:34:02,540 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:03,363 - root - ERROR - ('362103', 'not_found')
2021-09-22 19:34:03,364 - root - ERROR - list index out of range
2021-09-22 19:34:03,365 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:04,483 - root - ERROR - ('362121', 'not_found')
2021-09-22 19:34:04,483 - root - ERROR - list index out of range
2021-09-22 19:34:04,483 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:05,608 - root - ERROR - ('362122', 'not_found')
2021-09-22 19:34:05,608 - root - ERROR - list index out of range
2021-09-22 19:34:05,608 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:06,326 - root - ERROR - ('362123', 'not_found')
2021-09-22 19:34:06,326 - root - ERROR - list index out of range
2021-09-22 19:34:06,326 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:07,452 - root - ERROR - ('362124', 'not_found')
2021-09-22 19:34:07,452 - root - ERROR - list index out of range
2021-09-22 19:34:07,452 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:08,579 - root - ERROR - ('362125', 'not_found')
2021-09-22 19:34:08,580 - root - ERROR - list index out of range
2021-09-22 19:34:08,580 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:09,704 - root - ERROR - ('362126', 'not_found')
2021-09-22 19:34:09,704 - root - ERROR - list index out of range
2021-09-22 19:34:09,704 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:10,833 - root - ERROR - ('362127', 'not_found')
2021-09-22 19:34:10,833 - root - ERROR - list index out of range
2021-09-22 19:34:10,833 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:11,548 - root - ERROR - ('362128', 'not_found')
2021-09-22 19:34:11,548 - root - ERROR - list index out of range
2021-09-22 19:34:11,548 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:12,676 - root - ERROR - ('362129', 'not_found')
2021-09-22 19:34:12,676 - root - ERROR - list index out of range
2021-09-22 19:34:12,677 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:13,803 - root - ERROR - ('362130', 'not_found')
2021-09-22 19:34:13,804 - root - ERROR - list index out of range
2021-09-22 19:34:13,804 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:14,931 - root - ERROR - ('362131', 'not_found')
2021-09-22 19:34:14,931 - root - ERROR - list index out of range
2021-09-22 19:34:14,931 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:16,055 - root - ERROR - ('362132', 'not_found')
2021-09-22 19:34:16,056 - root - ERROR - list index out of range
2021-09-22 19:34:16,056 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:17,181 - root - ERROR - ('362133', 'not_found')
2021-09-22 19:34:17,182 - root - ERROR - list index out of range
2021-09-22 19:34:17,182 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:18,923 - root - ERROR - ('362134', 'not_found')
2021-09-22 19:34:18,923 - root - ERROR - list index out of range
2021-09-22 19:34:18,923 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:20,048 - root - ERROR - ('362135', 'not_found')
2021-09-22 19:34:20,049 - root - ERROR - list index out of range
2021-09-22 19:34:20,049 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:20,866 - root - ERROR - ('362136', 'not_found')
2021-09-22 19:34:20,866 - root - ERROR - list index out of range
2021-09-22 19:34:20,866 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:21,583 - root - ERROR - ('362137', 'not_found')
2021-09-22 19:34:21,583 - root - ERROR - list index out of range
2021-09-22 19:34:21,583 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:22,302 - root - ERROR - ('362221', 'not_found')
2021-09-22 19:34:22,302 - root - ERROR - list index out of range
2021-09-22 19:34:22,302 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:23,427 - root - ERROR - ('362222', 'not_found')
2021-09-22 19:34:23,427 - root - ERROR - list index out of range
2021-09-22 19:34:23,427 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:24,245 - root - ERROR - ('362223', 'not_found')
2021-09-22 19:34:24,245 - root - ERROR - list index out of range
2021-09-22 19:34:24,245 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:24,965 - root - ERROR - ('362333', 'not_found')
2021-09-22 19:34:24,965 - root - ERROR - list index out of range
2021-09-22 19:34:24,966 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:26,088 - root - ERROR - ('362431', 'not_found')
2021-09-22 19:34:26,088 - root - ERROR - list index out of range
2021-09-22 19:34:26,088 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:27,219 - root - ERROR - ('362433', 'not_found')
2021-09-22 19:34:27,219 - root - ERROR - list index out of range
2021-09-22 19:34:27,219 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:27,931 - root - ERROR - ('362501', 'not_found')
2021-09-22 19:34:27,931 - root - ERROR - list index out of range
2021-09-22 19:34:27,931 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:29,060 - root - ERROR - ('370111', 'not_found')
2021-09-22 19:34:29,060 - root - ERROR - list index out of range
2021-09-22 19:34:29,060 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:29,775 - root - ERROR - ('370113', 'not_found')
2021-09-22 19:34:29,775 - root - ERROR - list index out of range
2021-09-22 19:34:29,775 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:30,492 - root - ERROR - ('370121', 'not_found')
2021-09-22 19:34:30,492 - root - ERROR - list index out of range
2021-09-22 19:34:30,492 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:31,905 - root - ERROR - ('370122', 'not_found')
2021-09-22 19:34:31,905 - root - ERROR - list index out of range
2021-09-22 19:34:31,906 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:33,003 - root - ERROR - ('370204', 'not_found')
2021-09-22 19:34:33,003 - root - ERROR - list index out of range
2021-09-22 19:34:33,004 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:34,186 - root - ERROR - ('370206', 'not_found')
2021-09-22 19:34:34,186 - root - ERROR - list index out of range
2021-09-22 19:34:34,186 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:35,305 - root - ERROR - ('370221', 'not_found')
2021-09-22 19:34:35,305 - root - ERROR - list index out of range
2021-09-22 19:34:35,305 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:36,376 - root - ERROR - ('370222', 'not_found')
2021-09-22 19:34:36,376 - root - ERROR - list index out of range
2021-09-22 19:34:36,376 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:37,150 - root - ERROR - ('370223', 'not_found')
2021-09-22 19:34:37,150 - root - ERROR - list index out of range
2021-09-22 19:34:37,150 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:37,967 - root - ERROR - ('370224', 'not_found')
2021-09-22 19:34:37,967 - root - ERROR - list index out of range
2021-09-22 19:34:37,967 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:38,786 - root - ERROR - ('370225', 'not_found')
2021-09-22 19:34:38,787 - root - ERROR - list index out of range
2021-09-22 19:34:38,787 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:39,505 - root - ERROR - ('370226', 'not_found')
2021-09-22 19:34:39,505 - root - ERROR - list index out of range
2021-09-22 19:34:39,506 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:40,225 - root - ERROR - ('370421', 'not_found')
2021-09-22 19:34:40,225 - root - ERROR - list index out of range
2021-09-22 19:34:40,225 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:40,938 - root - ERROR - ('370620', 'not_found')
2021-09-22 19:34:40,938 - root - ERROR - list index out of range
2021-09-22 19:34:40,938 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:42,476 - root - ERROR - ('370622', 'not_found')
2021-09-22 19:34:42,476 - root - ERROR - list index out of range
2021-09-22 19:34:42,477 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:43,602 - root - ERROR - ('370623', 'not_found')
2021-09-22 19:34:43,602 - root - ERROR - list index out of range
2021-09-22 19:34:43,602 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:44,726 - root - ERROR - ('370624', 'not_found')
2021-09-22 19:34:44,726 - root - ERROR - list index out of range
2021-09-22 19:34:44,726 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:45,853 - root - ERROR - ('370625', 'not_found')
2021-09-22 19:34:45,853 - root - ERROR - list index out of range
2021-09-22 19:34:45,853 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:46,979 - root - ERROR - ('370627', 'not_found')
2021-09-22 19:34:46,979 - root - ERROR - list index out of range
2021-09-22 19:34:46,979 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:47,698 - root - ERROR - ('370628', 'not_found')
2021-09-22 19:34:47,698 - root - ERROR - list index out of range
2021-09-22 19:34:47,698 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:48,719 - root - ERROR - ('370629', 'not_found')
2021-09-22 19:34:48,719 - root - ERROR - list index out of range
2021-09-22 19:34:48,719 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:49,439 - root - ERROR - ('370630', 'not_found')
2021-09-22 19:34:49,439 - root - ERROR - list index out of range
2021-09-22 19:34:49,440 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:50,562 - root - ERROR - ('370631', 'not_found')
2021-09-22 19:34:50,562 - root - ERROR - list index out of range
2021-09-22 19:34:50,562 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:51,650 - root - ERROR - ('370632', 'not_found')
2021-09-22 19:34:51,650 - root - ERROR - list index out of range
2021-09-22 19:34:51,651 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:52,399 - root - ERROR - ('370633', 'not_found')
2021-09-22 19:34:52,399 - root - ERROR - list index out of range
2021-09-22 19:34:52,400 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:53,431 - root - ERROR - ('370721', 'not_found')
2021-09-22 19:34:53,432 - root - ERROR - list index out of range
2021-09-22 19:34:53,432 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:54,248 - root - ERROR - ('370722', 'not_found')
2021-09-22 19:34:54,248 - root - ERROR - list index out of range
2021-09-22 19:34:54,248 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:55,377 - root - ERROR - ('370723', 'not_found')
2021-09-22 19:34:55,378 - root - ERROR - list index out of range
2021-09-22 19:34:55,378 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:56,501 - root - ERROR - ('370726', 'not_found')
2021-09-22 19:34:56,501 - root - ERROR - list index out of range
2021-09-22 19:34:56,501 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:57,630 - root - ERROR - ('370727', 'not_found')
2021-09-22 19:34:57,631 - root - ERROR - list index out of range
2021-09-22 19:34:57,632 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:34:58,754 - root - ERROR - ('370728', 'not_found')
2021-09-22 19:34:58,754 - root - ERROR - list index out of range
2021-09-22 19:34:58,754 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:00,291 - root - ERROR - ('370729', 'not_found')
2021-09-22 19:35:00,291 - root - ERROR - list index out of range
2021-09-22 19:35:00,291 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:01,419 - root - ERROR - ('370822', 'not_found')
2021-09-22 19:35:01,419 - root - ERROR - list index out of range
2021-09-22 19:35:01,420 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:02,545 - root - ERROR - ('370823', 'not_found')
2021-09-22 19:35:02,545 - root - ERROR - list index out of range
2021-09-22 19:35:02,545 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:03,670 - root - ERROR - ('370825', 'not_found')
2021-09-22 19:35:03,670 - root - ERROR - list index out of range
2021-09-22 19:35:03,670 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:04,386 - root - ERROR - ('370903', 'not_found')
2021-09-22 19:35:04,386 - root - ERROR - list index out of range
2021-09-22 19:35:04,386 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:05,516 - root - ERROR - ('370919', 'not_found')
2021-09-22 19:35:05,516 - root - ERROR - list index out of range
2021-09-22 19:35:05,517 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:06,639 - root - ERROR - ('370920', 'not_found')
2021-09-22 19:35:06,639 - root - ERROR - list index out of range
2021-09-22 19:35:06,639 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:07,373 - root - ERROR - ('370922', 'not_found')
2021-09-22 19:35:07,373 - root - ERROR - list index out of range
2021-09-22 19:35:07,373 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:08,073 - root - ERROR - ('371021', 'not_found')
2021-09-22 19:35:08,073 - root - ERROR - list index out of range
2021-09-22 19:35:08,073 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:08,790 - root - ERROR - ('371103', 'not_found')
2021-09-22 19:35:08,790 - root - ERROR - list index out of range
2021-09-22 19:35:08,790 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:09,507 - root - ERROR - ('371621', 'not_found')
2021-09-22 19:35:09,507 - root - ERROR - list index out of range
2021-09-22 19:35:09,508 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:10,325 - root - ERROR - ('371623', 'not_found')
2021-09-22 19:35:10,325 - root - ERROR - list index out of range
2021-09-22 19:35:10,325 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:11,042 - root - ERROR - ('371721', 'not_found')
2021-09-22 19:35:11,042 - root - ERROR - list index out of range
2021-09-22 19:35:11,042 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:12,085 - root - ERROR - ('371722', 'not_found')
2021-09-22 19:35:12,085 - root - ERROR - list index out of range
2021-09-22 19:35:12,085 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:13,192 - root - ERROR - ('371725', 'not_found')
2021-09-22 19:35:13,192 - root - ERROR - list index out of range
2021-09-22 19:35:13,192 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:14,253 - root - ERROR - ('371726', 'not_found')
2021-09-22 19:35:14,255 - root - ERROR - list index out of range
2021-09-22 19:35:14,255 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:15,142 - root - ERROR - ('371727', 'not_found')
2021-09-22 19:35:15,142 - root - ERROR - list index out of range
2021-09-22 19:35:15,143 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:16,265 - root - ERROR - ('371728', 'not_found')
2021-09-22 19:35:16,265 - root - ERROR - list index out of range
2021-09-22 19:35:16,265 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:17,394 - root - ERROR - ('372331', 'not_found')
2021-09-22 19:35:17,394 - root - ERROR - list index out of range
2021-09-22 19:35:17,394 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:18,081 - root - ERROR - ('372401', 'not_found')
2021-09-22 19:35:18,081 - root - ERROR - list index out of range
2021-09-22 19:35:18,081 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:19,235 - root - ERROR - ('372402', 'not_found')
2021-09-22 19:35:19,235 - root - ERROR - list index out of range
2021-09-22 19:35:19,235 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:35:20,360 - root - ERROR - ('372421', 'not_found')
2021-09-22 19:35:20,360 - root - ERROR - list index out of range
2021-09-22 19:35:20,360 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:34,420 - root - ERROR - ('420506', 'not_found')
2021-09-22 19:39:34,420 - root - ERROR - list index out of range
2021-09-22 19:39:34,420 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:35,544 - root - ERROR - ('420523', 'not_found')
2021-09-22 19:39:35,544 - root - ERROR - list index out of range
2021-09-22 19:39:35,545 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:36,669 - root - ERROR - ('420603', 'not_found')
2021-09-22 19:39:36,669 - root - ERROR - list index out of range
2021-09-22 19:39:36,669 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:37,795 - root - ERROR - ('420604', 'not_found')
2021-09-22 19:39:37,795 - root - ERROR - list index out of range
2021-09-22 19:39:37,795 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:38,626 - root - ERROR - ('420605', 'not_found')
2021-09-22 19:39:38,627 - root - ERROR - list index out of range
2021-09-22 19:39:38,627 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:39,741 - root - ERROR - ('420607', 'not_found')
2021-09-22 19:39:39,741 - root - ERROR - list index out of range
2021-09-22 19:39:39,741 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:40,550 - root - ERROR - ('420619', 'not_found')
2021-09-22 19:39:40,550 - root - ERROR - list index out of range
2021-09-22 19:39:40,550 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:41,380 - root - ERROR - ('420620', 'not_found')
2021-09-22 19:39:41,380 - root - ERROR - list index out of range
2021-09-22 19:39:41,380 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:42,509 - root - ERROR - ('420622', 'not_found')
2021-09-22 19:39:42,509 - root - ERROR - list index out of range
2021-09-22 19:39:42,509 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:46,909 - root - ERROR - ('420623', 'not_found')
2021-09-22 19:39:46,909 - root - ERROR - list index out of range
2021-09-22 19:39:46,909 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:47,626 - root - ERROR - ('420803', 'not_found')
2021-09-22 19:39:47,626 - root - ERROR - list index out of range
2021-09-22 19:39:47,626 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:48,427 - root - ERROR - ('420804', 'not_found')
2021-09-22 19:39:48,427 - root - ERROR - list index out of range
2021-09-22 19:39:48,427 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:49,572 - root - ERROR - ('421004', 'not_found')
2021-09-22 19:39:49,572 - root - ERROR - list index out of range
2021-09-22 19:39:49,572 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:50,289 - root - ERROR - ('421281', 'not_found')
2021-09-22 19:39:50,289 - root - ERROR - list index out of range
2021-09-22 19:39:50,289 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:51,005 - root - ERROR - ('421302', 'not_found')
2021-09-22 19:39:51,005 - root - ERROR - list index out of range
2021-09-22 19:39:51,006 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:52,139 - root - ERROR - ('421381', 'not_found')
2021-09-22 19:39:52,139 - root - ERROR - list index out of range
2021-09-22 19:39:52,139 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:52,954 - root - ERROR - ('422101', 'not_found')
2021-09-22 19:39:52,955 - root - ERROR - list index out of range
2021-09-22 19:39:52,955 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:53,770 - root - ERROR - ('422103', 'not_found')
2021-09-22 19:39:53,770 - root - ERROR - list index out of range
2021-09-22 19:39:53,770 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:54,597 - root - ERROR - ('422121', 'not_found')
2021-09-22 19:39:54,597 - root - ERROR - list index out of range
2021-09-22 19:39:54,597 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:55,311 - root - ERROR - ('422123', 'not_found')
2021-09-22 19:39:55,311 - root - ERROR - list index out of range
2021-09-22 19:39:55,312 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:56,029 - root - ERROR - ('422124', 'not_found')
2021-09-22 19:39:56,030 - root - ERROR - list index out of range
2021-09-22 19:39:56,030 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:57,153 - root - ERROR - ('422125', 'not_found')
2021-09-22 19:39:57,153 - root - ERROR - list index out of range
2021-09-22 19:39:57,153 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:58,276 - root - ERROR - ('422126', 'not_found')
2021-09-22 19:39:58,276 - root - ERROR - list index out of range
2021-09-22 19:39:58,276 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:59,099 - root - ERROR - ('422127', 'not_found')
2021-09-22 19:39:59,100 - root - ERROR - list index out of range
2021-09-22 19:39:59,100 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:39:59,914 - root - ERROR - ('422128', 'not_found')
2021-09-22 19:39:59,914 - root - ERROR - list index out of range
2021-09-22 19:39:59,914 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:01,041 - root - ERROR - ('422129', 'not_found')
2021-09-22 19:40:01,041 - root - ERROR - list index out of range
2021-09-22 19:40:01,041 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:02,073 - root - ERROR - ('422130', 'not_found')
2021-09-22 19:40:02,073 - root - ERROR - list index out of range
2021-09-22 19:40:02,073 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:02,767 - root - ERROR - ('422201', 'not_found')
2021-09-22 19:40:02,767 - root - ERROR - list index out of range
2021-09-22 19:40:02,768 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:03,908 - root - ERROR - ('422202', 'not_found')
2021-09-22 19:40:03,908 - root - ERROR - list index out of range
2021-09-22 19:40:03,908 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:04,628 - root - ERROR - ('422203', 'not_found')
2021-09-22 19:40:04,629 - root - ERROR - list index out of range
2021-09-22 19:40:04,629 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:05,754 - root - ERROR - ('422204', 'not_found')
2021-09-22 19:40:05,754 - root - ERROR - list index out of range
2021-09-22 19:40:05,754 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:06,481 - root - ERROR - ('422221', 'not_found')
2021-09-22 19:40:06,481 - root - ERROR - list index out of range
2021-09-22 19:40:06,481 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:07,188 - root - ERROR - ('422223', 'not_found')
2021-09-22 19:40:07,188 - root - ERROR - list index out of range
2021-09-22 19:40:07,188 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:07,902 - root - ERROR - ('422224', 'not_found')
2021-09-22 19:40:07,902 - root - ERROR - list index out of range
2021-09-22 19:40:07,902 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:08,618 - root - ERROR - ('422225', 'not_found')
2021-09-22 19:40:08,618 - root - ERROR - list index out of range
2021-09-22 19:40:08,618 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:09,439 - root - ERROR - ('422226', 'not_found')
2021-09-22 19:40:09,440 - root - ERROR - list index out of range
2021-09-22 19:40:09,440 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:11,181 - root - ERROR - ('422228', 'not_found')
2021-09-22 19:40:11,181 - root - ERROR - list index out of range
2021-09-22 19:40:11,181 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:12,305 - root - ERROR - ('422301', 'not_found')
2021-09-22 19:40:12,305 - root - ERROR - list index out of range
2021-09-22 19:40:12,305 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:13,431 - root - ERROR - ('422302', 'not_found')
2021-09-22 19:40:13,431 - root - ERROR - list index out of range
2021-09-22 19:40:13,431 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:14,158 - root - ERROR - ('422322', 'not_found')
2021-09-22 19:40:14,158 - root - ERROR - list index out of range
2021-09-22 19:40:14,159 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:15,274 - root - ERROR - ('422323', 'not_found')
2021-09-22 19:40:15,274 - root - ERROR - list index out of range
2021-09-22 19:40:15,274 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:16,401 - root - ERROR - ('422324', 'not_found')
2021-09-22 19:40:16,401 - root - ERROR - list index out of range
2021-09-22 19:40:16,401 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:17,120 - root - ERROR - ('422325', 'not_found')
2021-09-22 19:40:17,121 - root - ERROR - list index out of range
2021-09-22 19:40:17,121 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:18,039 - root - ERROR - ('422326', 'not_found')
2021-09-22 19:40:18,039 - root - ERROR - list index out of range
2021-09-22 19:40:18,039 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:18,757 - root - ERROR - ('422327', 'not_found')
2021-09-22 19:40:18,758 - root - ERROR - list index out of range
2021-09-22 19:40:18,758 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:19,577 - root - ERROR - ('422400', 'not_found')
2021-09-22 19:40:19,577 - root - ERROR - list index out of range
2021-09-22 19:40:19,578 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:20,705 - root - ERROR - ('422401', 'not_found')
2021-09-22 19:40:20,705 - root - ERROR - list index out of range
2021-09-22 19:40:20,706 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:21,830 - root - ERROR - ('422403', 'not_found')
2021-09-22 19:40:21,830 - root - ERROR - list index out of range
2021-09-22 19:40:21,831 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:22,957 - root - ERROR - ('422406', 'not_found')
2021-09-22 19:40:22,957 - root - ERROR - list index out of range
2021-09-22 19:40:22,957 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:23,675 - root - ERROR - ('422421', 'not_found')
2021-09-22 19:40:23,675 - root - ERROR - list index out of range
2021-09-22 19:40:23,676 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:24,357 - root - ERROR - ('422422', 'not_found')
2021-09-22 19:40:24,357 - root - ERROR - list index out of range
2021-09-22 19:40:24,357 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:25,515 - root - ERROR - ('422423', 'not_found')
2021-09-22 19:40:25,515 - root - ERROR - list index out of range
2021-09-22 19:40:25,516 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:26,641 - root - ERROR - ('422424', 'not_found')
2021-09-22 19:40:26,641 - root - ERROR - list index out of range
2021-09-22 19:40:26,641 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:27,769 - root - ERROR - ('422425', 'not_found')
2021-09-22 19:40:27,770 - root - ERROR - list index out of range
2021-09-22 19:40:27,770 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:28,900 - root - ERROR - ('422426', 'not_found')
2021-09-22 19:40:28,900 - root - ERROR - list index out of range
2021-09-22 19:40:28,901 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:30,021 - root - ERROR - ('422427', 'not_found')
2021-09-22 19:40:30,021 - root - ERROR - list index out of range
2021-09-22 19:40:30,021 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:30,840 - root - ERROR - ('422428', 'not_found')
2021-09-22 19:40:30,840 - root - ERROR - list index out of range
2021-09-22 19:40:30,840 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:31,966 - root - ERROR - ('422429', 'not_found')
2021-09-22 19:40:31,966 - root - ERROR - list index out of range
2021-09-22 19:40:31,967 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:33,037 - root - ERROR - ('422431', 'not_found')
2021-09-22 19:40:33,037 - root - ERROR - list index out of range
2021-09-22 19:40:33,037 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:33,809 - root - ERROR - ('422432', 'not_found')
2021-09-22 19:40:33,809 - root - ERROR - list index out of range
2021-09-22 19:40:33,809 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:34,935 - root - ERROR - ('422601', 'not_found')
2021-09-22 19:40:34,935 - root - ERROR - list index out of range
2021-09-22 19:40:34,935 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:35,756 - root - ERROR - ('422622', 'not_found')
2021-09-22 19:40:35,757 - root - ERROR - list index out of range
2021-09-22 19:40:35,757 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:36,881 - root - ERROR - ('422623', 'not_found')
2021-09-22 19:40:36,881 - root - ERROR - list index out of range
2021-09-22 19:40:36,881 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:38,008 - root - ERROR - ('422624', 'not_found')
2021-09-22 19:40:38,008 - root - ERROR - list index out of range
2021-09-22 19:40:38,009 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:39,133 - root - ERROR - ('422625', 'not_found')
2021-09-22 19:40:39,133 - root - ERROR - list index out of range
2021-09-22 19:40:39,133 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:39,852 - root - ERROR - ('422626', 'not_found')
2021-09-22 19:40:39,852 - root - ERROR - list index out of range
2021-09-22 19:40:39,852 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:40,568 - root - ERROR - ('422701', 'not_found')
2021-09-22 19:40:40,568 - root - ERROR - list index out of range
2021-09-22 19:40:40,568 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:41,697 - root - ERROR - ('422702', 'not_found')
2021-09-22 19:40:41,698 - root - ERROR - list index out of range
2021-09-22 19:40:41,698 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:42,762 - root - ERROR - ('422721', 'not_found')
2021-09-22 19:40:42,763 - root - ERROR - list index out of range
2021-09-22 19:40:42,763 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:44,159 - root - ERROR - ('422722', 'not_found')
2021-09-22 19:40:44,159 - root - ERROR - list index out of range
2021-09-22 19:40:44,160 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:45,585 - root - ERROR - ('422723', 'not_found')
2021-09-22 19:40:45,585 - root - ERROR - list index out of range
2021-09-22 19:40:45,585 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:46,404 - root - ERROR - ('422724', 'not_found')
2021-09-22 19:40:46,404 - root - ERROR - list index out of range
2021-09-22 19:40:46,404 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:47,121 - root - ERROR - ('422725', 'not_found')
2021-09-22 19:40:47,122 - root - ERROR - list index out of range
2021-09-22 19:40:47,122 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:48,046 - root - ERROR - ('422726', 'not_found')
2021-09-22 19:40:48,047 - root - ERROR - list index out of range
2021-09-22 19:40:48,047 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:48,863 - root - ERROR - ('422727', 'not_found')
2021-09-22 19:40:48,863 - root - ERROR - list index out of range
2021-09-22 19:40:48,864 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:49,988 - root - ERROR - ('422728', 'not_found')
2021-09-22 19:40:49,988 - root - ERROR - list index out of range
2021-09-22 19:40:49,988 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:51,114 - root - ERROR - ('422729', 'not_found')
2021-09-22 19:40:51,114 - root - ERROR - list index out of range
2021-09-22 19:40:51,114 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:52,144 - root - ERROR - ('422921', 'not_found')
2021-09-22 19:40:52,144 - root - ERROR - list index out of range
2021-09-22 19:40:52,144 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:53,267 - root - ERROR - ('423020', 'not_found')
2021-09-22 19:40:53,268 - root - ERROR - list index out of range
2021-09-22 19:40:53,268 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:54,391 - root - ERROR - ('430123', 'not_found')
2021-09-22 19:40:54,391 - root - ERROR - list index out of range
2021-09-22 19:40:54,391 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:55,416 - root - ERROR - ('430219', 'not_found')
2021-09-22 19:40:55,416 - root - ERROR - list index out of range
2021-09-22 19:40:55,416 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:58,794 - root - ERROR - ('430305', 'not_found')
2021-09-22 19:40:58,794 - root - ERROR - list index out of range
2021-09-22 19:40:58,794 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:40:59,921 - root - ERROR - ('430311', 'not_found')
2021-09-22 19:40:59,921 - root - ERROR - list index out of range
2021-09-22 19:40:59,921 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:01,002 - root - ERROR - ('430312', 'not_found')
2021-09-22 19:41:01,002 - root - ERROR - list index out of range
2021-09-22 19:41:01,002 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:02,109 - root - ERROR - ('430322', 'not_found')
2021-09-22 19:41:02,109 - root - ERROR - list index out of range
2021-09-22 19:41:02,109 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:03,229 - root - ERROR - ('430405', 'not_found')
2021-09-22 19:41:03,229 - root - ERROR - list index out of range
2021-09-22 19:41:03,229 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:04,226 - root - ERROR - ('430406', 'not_found')
2021-09-22 19:41:04,226 - root - ERROR - list index out of range
2021-09-22 19:41:04,226 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:04,915 - root - ERROR - ('430407', 'not_found')
2021-09-22 19:41:04,915 - root - ERROR - list index out of range
2021-09-22 19:41:04,915 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:05,528 - root - ERROR - ('430408', 'not_found')
2021-09-22 19:41:05,529 - root - ERROR - list index out of range
2021-09-22 19:41:05,529 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:06,224 - root - ERROR - ('430419', 'not_found')
2021-09-22 19:41:06,224 - root - ERROR - list index out of range
2021-09-22 19:41:06,224 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:06,942 - root - ERROR - ('430425', 'not_found')
2021-09-22 19:41:06,942 - root - ERROR - list index out of range
2021-09-22 19:41:06,942 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:07,589 - root - ERROR - ('430526', 'not_found')
2021-09-22 19:41:07,589 - root - ERROR - list index out of range
2021-09-22 19:41:07,589 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:08,727 - root - ERROR - ('430622', 'not_found')
2021-09-22 19:41:08,727 - root - ERROR - list index out of range
2021-09-22 19:41:08,727 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:09,446 - root - ERROR - ('430625', 'not_found')
2021-09-22 19:41:09,446 - root - ERROR - list index out of range
2021-09-22 19:41:09,447 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:10,468 - root - ERROR - ('430911', 'not_found')
2021-09-22 19:41:10,468 - root - ERROR - list index out of range
2021-09-22 19:41:10,468 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:11,115 - root - ERROR - ('431302', 'not_found')
2021-09-22 19:41:11,115 - root - ERROR - list index out of range
2021-09-22 19:41:11,115 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:12,208 - root - ERROR - ('431321', 'not_found')
2021-09-22 19:41:12,208 - root - ERROR - list index out of range
2021-09-22 19:41:12,209 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:13,212 - root - ERROR - ('431322', 'not_found')
2021-09-22 19:41:13,212 - root - ERROR - list index out of range
2021-09-22 19:41:13,212 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:14,345 - root - ERROR - ('431381', 'not_found')
2021-09-22 19:41:14,345 - root - ERROR - list index out of range
2021-09-22 19:41:14,345 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:15,487 - root - ERROR - ('431382', 'not_found')
2021-09-22 19:41:15,487 - root - ERROR - list index out of range
2021-09-22 19:41:15,488 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:16,542 - root - ERROR - ('432301', 'not_found')
2021-09-22 19:41:16,542 - root - ERROR - list index out of range
2021-09-22 19:41:16,542 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:17,601 - root - ERROR - ('432302', 'not_found')
2021-09-22 19:41:17,601 - root - ERROR - list index out of range
2021-09-22 19:41:17,602 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:18,592 - root - ERROR - ('432321', 'not_found')
2021-09-22 19:41:18,592 - root - ERROR - list index out of range
2021-09-22 19:41:18,592 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:19,607 - root - ERROR - ('432322', 'not_found')
2021-09-22 19:41:19,608 - root - ERROR - list index out of range
2021-09-22 19:41:19,608 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:20,402 - root - ERROR - ('432325', 'not_found')
2021-09-22 19:41:20,403 - root - ERROR - list index out of range
2021-09-22 19:41:20,403 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:21,137 - root - ERROR - ('432326', 'not_found')
2021-09-22 19:41:21,137 - root - ERROR - list index out of range
2021-09-22 19:41:21,138 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:22,212 - root - ERROR - ('432401', 'not_found')
2021-09-22 19:41:22,213 - root - ERROR - list index out of range
2021-09-22 19:41:22,213 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:22,929 - root - ERROR - ('432402', 'not_found')
2021-09-22 19:41:22,929 - root - ERROR - list index out of range
2021-09-22 19:41:22,929 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:23,947 - root - ERROR - ('432421', 'not_found')
2021-09-22 19:41:23,947 - root - ERROR - list index out of range
2021-09-22 19:41:23,947 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:24,624 - root - ERROR - ('432422', 'not_found')
2021-09-22 19:41:24,625 - root - ERROR - list index out of range
2021-09-22 19:41:24,625 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:25,627 - root - ERROR - ('432423', 'not_found')
2021-09-22 19:41:25,627 - root - ERROR - list index out of range
2021-09-22 19:41:25,627 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:26,297 - root - ERROR - ('432424', 'not_found')
2021-09-22 19:41:26,298 - root - ERROR - list index out of range
2021-09-22 19:41:26,298 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:27,051 - root - ERROR - ('432425', 'not_found')
2021-09-22 19:41:27,051 - root - ERROR - list index out of range
2021-09-22 19:41:27,052 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:28,054 - root - ERROR - ('432426', 'not_found')
2021-09-22 19:41:28,054 - root - ERROR - list index out of range
2021-09-22 19:41:28,054 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:28,798 - root - ERROR - ('432427', 'not_found')
2021-09-22 19:41:28,798 - root - ERROR - list index out of range
2021-09-22 19:41:28,798 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:29,518 - root - ERROR - ('432428', 'not_found')
2021-09-22 19:41:29,518 - root - ERROR - list index out of range
2021-09-22 19:41:29,518 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:30,582 - root - ERROR - ('432526', 'not_found')
2021-09-22 19:41:30,582 - root - ERROR - list index out of range
2021-09-22 19:41:30,582 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:31,769 - root - ERROR - ('432621', 'not_found')
2021-09-22 19:41:31,769 - root - ERROR - list index out of range
2021-09-22 19:41:31,769 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:32,484 - root - ERROR - ('432622', 'not_found')
2021-09-22 19:41:32,484 - root - ERROR - list index out of range
2021-09-22 19:41:32,484 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:33,519 - root - ERROR - ('432623', 'not_found')
2021-09-22 19:41:33,519 - root - ERROR - list index out of range
2021-09-22 19:41:33,519 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:34,511 - root - ERROR - ('432624', 'not_found')
2021-09-22 19:41:34,511 - root - ERROR - list index out of range
2021-09-22 19:41:34,511 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:35,762 - root - ERROR - ('432625', 'not_found')
2021-09-22 19:41:35,762 - root - ERROR - list index out of range
2021-09-22 19:41:35,762 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:36,805 - root - ERROR - ('432626', 'not_found')
2021-09-22 19:41:36,805 - root - ERROR - list index out of range
2021-09-22 19:41:36,806 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:37,604 - root - ERROR - ('432627', 'not_found')
2021-09-22 19:41:37,604 - root - ERROR - list index out of range
2021-09-22 19:41:37,604 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:38,914 - root - ERROR - ('432725', 'not_found')
2021-09-22 19:41:38,914 - root - ERROR - list index out of range
2021-09-22 19:41:38,914 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:39,755 - root - ERROR - ('432801', 'not_found')
2021-09-22 19:41:39,755 - root - ERROR - list index out of range
2021-09-22 19:41:39,755 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:40,475 - root - ERROR - ('432802', 'not_found')
2021-09-22 19:41:40,475 - root - ERROR - list index out of range
2021-09-22 19:41:40,475 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:41,291 - root - ERROR - ('432821', 'not_found')
2021-09-22 19:41:41,291 - root - ERROR - list index out of range
2021-09-22 19:41:41,291 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:42,417 - root - ERROR - ('432822', 'not_found')
2021-09-22 19:41:42,417 - root - ERROR - list index out of range
2021-09-22 19:41:42,417 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:41:43,544 - root - ERROR - ('432823', 'not_found')
2021-09-22 19:41:43,544 - root - ERROR - list index out of range
2021-09-22 19:41:43,544 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:21,557 - root - ERROR - ('441811', 'not_found')
2021-09-22 19:45:21,557 - root - ERROR - list index out of range
2021-09-22 19:45:21,557 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:22,682 - root - ERROR - ('441822', 'not_found')
2021-09-22 19:45:22,682 - root - ERROR - list index out of range
2021-09-22 19:45:22,682 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:23,810 - root - ERROR - ('441824', 'not_found')
2021-09-22 19:45:23,810 - root - ERROR - list index out of range
2021-09-22 19:45:23,810 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:24,934 - root - ERROR - ('442501', 'not_found')
2021-09-22 19:45:24,934 - root - ERROR - list index out of range
2021-09-22 19:45:24,934 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:25,961 - root - ERROR - ('442521', 'not_found')
2021-09-22 19:45:25,961 - root - ERROR - list index out of range
2021-09-22 19:45:25,961 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:27,086 - root - ERROR - ('442522', 'not_found')
2021-09-22 19:45:27,086 - root - ERROR - list index out of range
2021-09-22 19:45:27,087 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:28,219 - root - ERROR - ('442523', 'not_found')
2021-09-22 19:45:28,219 - root - ERROR - list index out of range
2021-09-22 19:45:28,220 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:29,337 - root - ERROR - ('442524', 'not_found')
2021-09-22 19:45:29,337 - root - ERROR - list index out of range
2021-09-22 19:45:29,337 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:30,471 - root - ERROR - ('442525', 'not_found')
2021-09-22 19:45:30,471 - root - ERROR - list index out of range
2021-09-22 19:45:30,472 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:31,514 - root - ERROR - ('442526', 'not_found')
2021-09-22 19:45:31,514 - root - ERROR - list index out of range
2021-09-22 19:45:31,515 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:32,210 - root - ERROR - ('442527', 'not_found')
2021-09-22 19:45:32,210 - root - ERROR - list index out of range
2021-09-22 19:45:32,210 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:33,245 - root - ERROR - ('442528', 'not_found')
2021-09-22 19:45:33,245 - root - ERROR - list index out of range
2021-09-22 19:45:33,245 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:34,047 - root - ERROR - ('442529', 'not_found')
2021-09-22 19:45:34,047 - root - ERROR - list index out of range
2021-09-22 19:45:34,047 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:34,764 - root - ERROR - ('442530', 'not_found')
2021-09-22 19:45:34,764 - root - ERROR - list index out of range
2021-09-22 19:45:34,764 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:35,583 - root - ERROR - ('442531', 'not_found')
2021-09-22 19:45:35,583 - root - ERROR - list index out of range
2021-09-22 19:45:35,583 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:36,404 - root - ERROR - ('442801', 'not_found')
2021-09-22 19:45:36,404 - root - ERROR - list index out of range
2021-09-22 19:45:36,404 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:37,529 - root - ERROR - ('442821', 'not_found')
2021-09-22 19:45:37,529 - root - ERROR - list index out of range
2021-09-22 19:45:37,529 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:38,656 - root - ERROR - ('442822', 'not_found')
2021-09-22 19:45:38,656 - root - ERROR - list index out of range
2021-09-22 19:45:38,656 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:39,783 - root - ERROR - ('442823', 'not_found')
2021-09-22 19:45:39,784 - root - ERROR - list index out of range
2021-09-22 19:45:39,784 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:40,500 - root - ERROR - ('442824', 'not_found')
2021-09-22 19:45:40,501 - root - ERROR - list index out of range
2021-09-22 19:45:40,501 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:41,625 - root - ERROR - ('442825', 'not_found')
2021-09-22 19:45:41,625 - root - ERROR - list index out of range
2021-09-22 19:45:41,625 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:42,753 - root - ERROR - ('442826', 'not_found')
2021-09-22 19:45:42,753 - root - ERROR - list index out of range
2021-09-22 19:45:42,753 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:43,470 - root - ERROR - ('442827', 'not_found')
2021-09-22 19:45:43,470 - root - ERROR - list index out of range
2021-09-22 19:45:43,470 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:44,287 - root - ERROR - ('442828', 'not_found')
2021-09-22 19:45:44,287 - root - ERROR - list index out of range
2021-09-22 19:45:44,287 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:45,414 - root - ERROR - ('442829', 'not_found')
2021-09-22 19:45:45,414 - root - ERROR - list index out of range
2021-09-22 19:45:45,414 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:46,131 - root - ERROR - ('442830', 'not_found')
2021-09-22 19:45:46,133 - root - ERROR - list index out of range
2021-09-22 19:45:46,134 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:47,248 - root - ERROR - ('445223', 'not_found')
2021-09-22 19:45:47,248 - root - ERROR - list index out of range
2021-09-22 19:45:47,249 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:48,079 - root - ERROR - ('450109', 'not_found')
2021-09-22 19:45:48,079 - root - ERROR - list index out of range
2021-09-22 19:45:48,079 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:48,895 - root - ERROR - ('450124', 'not_found')
2021-09-22 19:45:48,895 - root - ERROR - list index out of range
2021-09-22 19:45:48,895 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:49,614 - root - ERROR - ('450125', 'not_found')
2021-09-22 19:45:49,615 - root - ERROR - list index out of range
2021-09-22 19:45:49,615 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:50,741 - root - ERROR - ('450126', 'not_found')
2021-09-22 19:45:50,742 - root - ERROR - list index out of range
2021-09-22 19:45:50,742 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:51,561 - root - ERROR - ('450127', 'not_found')
2021-09-22 19:45:51,562 - root - ERROR - list index out of range
2021-09-22 19:45:51,563 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:52,382 - root - ERROR - ('450223', 'not_found')
2021-09-22 19:45:52,382 - root - ERROR - list index out of range
2021-09-22 19:45:52,383 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:53,508 - root - ERROR - ('450224', 'not_found')
2021-09-22 19:45:53,509 - root - ERROR - list index out of range
2021-09-22 19:45:53,509 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:54,328 - root - ERROR - ('450226', 'not_found')
2021-09-22 19:45:54,328 - root - ERROR - list index out of range
2021-09-22 19:45:54,329 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:55,146 - root - ERROR - ('450402', 'not_found')
2021-09-22 19:45:55,146 - root - ERROR - list index out of range
2021-09-22 19:45:55,146 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:56,233 - root - ERROR - ('450511', 'not_found')
2021-09-22 19:45:56,233 - root - ERROR - list index out of range
2021-09-22 19:45:56,233 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:57,404 - root - ERROR - ('450525', 'not_found')
2021-09-22 19:45:57,404 - root - ERROR - list index out of range
2021-09-22 19:45:57,405 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:58,222 - root - ERROR - ('450804', 'not_found')
2021-09-22 19:45:58,222 - root - ERROR - list index out of range
2021-09-22 19:45:58,222 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:45:59,341 - root - ERROR - ('451024', 'not_found')
2021-09-22 19:45:59,341 - root - ERROR - list index out of range
2021-09-22 19:45:59,341 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:00,474 - root - ERROR - ('451227', 'not_found')
2021-09-22 19:46:00,474 - root - ERROR - list index out of range
2021-09-22 19:46:00,476 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:01,294 - root - ERROR - ('451229', 'not_found')
2021-09-22 19:46:01,294 - root - ERROR - list index out of range
2021-09-22 19:46:01,295 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:02,517 - root - ERROR - ('451302', 'not_found')
2021-09-22 19:46:02,517 - root - ERROR - list index out of range
2021-09-22 19:46:02,518 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:03,574 - root - ERROR - ('451321', 'not_found')
2021-09-22 19:46:03,575 - root - ERROR - list index out of range
2021-09-22 19:46:03,575 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:04,388 - root - ERROR - ('451322', 'not_found')
2021-09-22 19:46:04,389 - root - ERROR - list index out of range
2021-09-22 19:46:04,390 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:05,077 - root - ERROR - ('451402', 'not_found')
2021-09-22 19:46:05,077 - root - ERROR - list index out of range
2021-09-22 19:46:05,077 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:06,209 - root - ERROR - ('451423', 'not_found')
2021-09-22 19:46:06,210 - root - ERROR - list index out of range
2021-09-22 19:46:06,210 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:07,331 - root - ERROR - ('451425', 'not_found')
2021-09-22 19:46:07,331 - root - ERROR - list index out of range
2021-09-22 19:46:07,331 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:08,029 - root - ERROR - ('452206', 'not_found')
2021-09-22 19:46:08,029 - root - ERROR - list index out of range
2021-09-22 19:46:08,030 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:08,778 - root - ERROR - ('452322', 'not_found')
2021-09-22 19:46:08,778 - root - ERROR - list index out of range
2021-09-22 19:46:08,779 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:09,585 - root - ERROR - ('452323', 'not_found')
2021-09-22 19:46:09,585 - root - ERROR - list index out of range
2021-09-22 19:46:09,585 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:10,408 - root - ERROR - ('452324', 'not_found')
2021-09-22 19:46:10,409 - root - ERROR - list index out of range
2021-09-22 19:46:10,410 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:11,123 - root - ERROR - ('452325', 'not_found')
2021-09-22 19:46:11,123 - root - ERROR - list index out of range
2021-09-22 19:46:11,124 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:12,245 - root - ERROR - ('452327', 'not_found')
2021-09-22 19:46:12,246 - root - ERROR - list index out of range
2021-09-22 19:46:12,246 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:13,366 - root - ERROR - ('452328', 'not_found')
2021-09-22 19:46:13,366 - root - ERROR - list index out of range
2021-09-22 19:46:13,366 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:14,499 - root - ERROR - ('452329', 'not_found')
2021-09-22 19:46:14,499 - root - ERROR - list index out of range
2021-09-22 19:46:14,500 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:15,624 - root - ERROR - ('452330', 'not_found')
2021-09-22 19:46:15,625 - root - ERROR - list index out of range
2021-09-22 19:46:15,625 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:21,699 - root - ERROR - ('452331', 'not_found')
2021-09-22 19:46:21,700 - root - ERROR - list index out of range
2021-09-22 19:46:21,700 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:22,419 - root - ERROR - ('452332', 'not_found')
2021-09-22 19:46:22,420 - root - ERROR - list index out of range
2021-09-22 19:46:22,420 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:23,430 - root - ERROR - ('452421', 'not_found')
2021-09-22 19:46:23,430 - root - ERROR - list index out of range
2021-09-22 19:46:23,431 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:24,431 - root - ERROR - ('452423', 'not_found')
2021-09-22 19:46:24,431 - root - ERROR - list index out of range
2021-09-22 19:46:24,432 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:25,478 - root - ERROR - ('452425', 'not_found')
2021-09-22 19:46:25,478 - root - ERROR - list index out of range
2021-09-22 19:46:25,479 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:26,431 - root - ERROR - ('452426', 'not_found')
2021-09-22 19:46:26,431 - root - ERROR - list index out of range
2021-09-22 19:46:26,431 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:27,505 - root - ERROR - ('452441', 'not_found')
2021-09-22 19:46:27,505 - root - ERROR - list index out of range
2021-09-22 19:46:27,505 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:28,222 - root - ERROR - ('452501', 'not_found')
2021-09-22 19:46:28,222 - root - ERROR - list index out of range
2021-09-22 19:46:28,222 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:28,940 - root - ERROR - ('452502', 'not_found')
2021-09-22 19:46:28,940 - root - ERROR - list index out of range
2021-09-22 19:46:28,941 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:30,062 - root - ERROR - ('452503', 'not_found')
2021-09-22 19:46:30,063 - root - ERROR - list index out of range
2021-09-22 19:46:30,063 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:31,193 - root - ERROR - ('452521', 'not_found')
2021-09-22 19:46:31,193 - root - ERROR - list index out of range
2021-09-22 19:46:31,193 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:32,315 - root - ERROR - ('452522', 'not_found')
2021-09-22 19:46:32,315 - root - ERROR - list index out of range
2021-09-22 19:46:32,315 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:33,414 - root - ERROR - ('452523', 'not_found')
2021-09-22 19:46:33,414 - root - ERROR - list index out of range
2021-09-22 19:46:33,414 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:46:34,434 - root - ERROR - ('452524', 'not_found')
2021-09-22 19:46:34,435 - root - ERROR - list index out of range
2021-09-22 19:46:34,435 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:30,190 - root - ERROR - ('511203', 'not_found')
2021-09-22 19:49:30,190 - root - ERROR - list index out of range
2021-09-22 19:49:30,191 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:31,315 - root - ERROR - ('511204', 'not_found')
2021-09-22 19:49:31,315 - root - ERROR - list index out of range
2021-09-22 19:49:31,316 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:32,438 - root - ERROR - ('511221', 'not_found')
2021-09-22 19:49:32,438 - root - ERROR - list index out of range
2021-09-22 19:49:32,439 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:33,160 - root - ERROR - ('511222', 'not_found')
2021-09-22 19:49:33,160 - root - ERROR - list index out of range
2021-09-22 19:49:33,161 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:34,283 - root - ERROR - ('511223', 'not_found')
2021-09-22 19:49:34,284 - root - ERROR - list index out of range
2021-09-22 19:49:34,284 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:34,999 - root - ERROR - ('511224', 'not_found')
2021-09-22 19:49:34,999 - root - ERROR - list index out of range
2021-09-22 19:49:35,000 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:35,718 - root - ERROR - ('511225', 'not_found')
2021-09-22 19:49:35,718 - root - ERROR - list index out of range
2021-09-22 19:49:35,719 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:36,846 - root - ERROR - ('511226', 'not_found')
2021-09-22 19:49:36,846 - root - ERROR - list index out of range
2021-09-22 19:49:36,847 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:37,665 - root - ERROR - ('511227', 'not_found')
2021-09-22 19:49:37,665 - root - ERROR - list index out of range
2021-09-22 19:49:37,666 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:38,480 - root - ERROR - ('511228', 'not_found')
2021-09-22 19:49:38,480 - root - ERROR - list index out of range
2021-09-22 19:49:38,481 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:39,709 - root - ERROR - ('511702', 'not_found')
2021-09-22 19:49:39,709 - root - ERROR - list index out of range
2021-09-22 19:49:39,710 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:40,420 - root - ERROR - ('511721', 'not_found')
2021-09-22 19:49:40,420 - root - ERROR - list index out of range
2021-09-22 19:49:40,421 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:41,249 - root - ERROR - ('511722', 'not_found')
2021-09-22 19:49:41,249 - root - ERROR - list index out of range
2021-09-22 19:49:41,250 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:41,963 - root - ERROR - ('511723', 'not_found')
2021-09-22 19:49:41,963 - root - ERROR - list index out of range
2021-09-22 19:49:41,963 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:42,682 - root - ERROR - ('511724', 'not_found')
2021-09-22 19:49:42,682 - root - ERROR - list index out of range
2021-09-22 19:49:42,683 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:43,399 - root - ERROR - ('511725', 'not_found')
2021-09-22 19:49:43,399 - root - ERROR - list index out of range
2021-09-22 19:49:43,400 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:44,103 - root - ERROR - ('511825', 'not_found')
2021-09-22 19:49:44,103 - root - ERROR - list index out of range
2021-09-22 19:49:44,104 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:44,834 - root - ERROR - ('511902', 'not_found')
2021-09-22 19:49:44,834 - root - ERROR - list index out of range
2021-09-22 19:49:44,835 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:45,651 - root - ERROR - ('511921', 'not_found')
2021-09-22 19:49:45,651 - root - ERROR - list index out of range
2021-09-22 19:49:45,652 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:46,779 - root - ERROR - ('511922', 'not_found')
2021-09-22 19:49:46,779 - root - ERROR - list index out of range
2021-09-22 19:49:46,780 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:47,904 - root - ERROR - ('511923', 'not_found')
2021-09-22 19:49:47,904 - root - ERROR - list index out of range
2021-09-22 19:49:47,905 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:49,368 - root - ERROR - ('512002', 'not_found')
2021-09-22 19:49:49,369 - root - ERROR - list index out of range
2021-09-22 19:49:49,370 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:50,159 - root - ERROR - ('512021', 'not_found')
2021-09-22 19:49:50,159 - root - ERROR - list index out of range
2021-09-22 19:49:50,159 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:51,279 - root - ERROR - ('512201', 'not_found')
2021-09-22 19:49:51,280 - root - ERROR - list index out of range
2021-09-22 19:49:51,280 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:51,998 - root - ERROR - ('512221', 'not_found')
2021-09-22 19:49:51,998 - root - ERROR - list index out of range
2021-09-22 19:49:51,998 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:52,717 - root - ERROR - ('512222', 'not_found')
2021-09-22 19:49:52,717 - root - ERROR - list index out of range
2021-09-22 19:49:52,718 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:53,435 - root - ERROR - ('512223', 'not_found')
2021-09-22 19:49:53,435 - root - ERROR - list index out of range
2021-09-22 19:49:53,436 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:54,139 - root - ERROR - ('512224', 'not_found')
2021-09-22 19:49:54,139 - root - ERROR - list index out of range
2021-09-22 19:49:54,140 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:54,936 - root - ERROR - ('512225', 'not_found')
2021-09-22 19:49:54,936 - root - ERROR - list index out of range
2021-09-22 19:49:54,937 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:56,204 - root - ERROR - ('512226', 'not_found')
2021-09-22 19:49:56,204 - root - ERROR - list index out of range
2021-09-22 19:49:56,206 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:57,120 - root - ERROR - ('512227', 'not_found')
2021-09-22 19:49:57,121 - root - ERROR - list index out of range
2021-09-22 19:49:57,122 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:57,941 - root - ERROR - ('512228', 'not_found')
2021-09-22 19:49:57,941 - root - ERROR - list index out of range
2021-09-22 19:49:57,942 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:49:59,678 - root - ERROR - ('512229', 'not_found')
2021-09-22 19:49:59,678 - root - ERROR - list index out of range
2021-09-22 19:49:59,678 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:00,804 - root - ERROR - ('512301', 'not_found')
2021-09-22 19:50:00,805 - root - ERROR - list index out of range
2021-09-22 19:50:00,805 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:01,212 - root - ERROR - ('512322', 'not_found')
2021-09-22 19:50:01,212 - root - ERROR - 'NoneType' object has no attribute 'xpath'
2021-09-22 19:50:01,213 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 242, in <module>
    eles = root.xpath("//div[@class='mcon f14 noi']/p[3]")
AttributeError: 'NoneType' object has no attribute 'xpath'

2021-09-22 19:50:02,242 - root - ERROR - ('512323', 'not_found')
2021-09-22 19:50:02,242 - root - ERROR - list index out of range
2021-09-22 19:50:02,243 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:03,363 - root - ERROR - ('512324', 'not_found')
2021-09-22 19:50:03,363 - root - ERROR - list index out of range
2021-09-22 19:50:03,363 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:04,066 - root - ERROR - ('512325', 'not_found')
2021-09-22 19:50:04,067 - root - ERROR - list index out of range
2021-09-22 19:50:04,067 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:04,801 - root - ERROR - ('512326', 'not_found')
2021-09-22 19:50:04,801 - root - ERROR - list index out of range
2021-09-22 19:50:04,801 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:05,621 - root - ERROR - ('512328', 'not_found')
2021-09-22 19:50:05,621 - root - ERROR - list index out of range
2021-09-22 19:50:05,622 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:06,743 - root - ERROR - ('512329', 'not_found')
2021-09-22 19:50:06,743 - root - ERROR - list index out of range
2021-09-22 19:50:06,743 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:07,869 - root - ERROR - ('512501', 'not_found')
2021-09-22 19:50:07,869 - root - ERROR - list index out of range
2021-09-22 19:50:07,869 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:08,996 - root - ERROR - ('512527', 'not_found')
2021-09-22 19:50:08,996 - root - ERROR - list index out of range
2021-09-22 19:50:08,996 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:09,824 - root - ERROR - ('512528', 'not_found')
2021-09-22 19:50:09,825 - root - ERROR - list index out of range
2021-09-22 19:50:09,826 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:10,942 - root - ERROR - ('512529', 'not_found')
2021-09-22 19:50:10,942 - root - ERROR - list index out of range
2021-09-22 19:50:10,943 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:12,071 - root - ERROR - ('512530', 'not_found')
2021-09-22 19:50:12,071 - root - ERROR - list index out of range
2021-09-22 19:50:12,072 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:13,195 - root - ERROR - ('512531', 'not_found')
2021-09-22 19:50:13,195 - root - ERROR - list index out of range
2021-09-22 19:50:13,195 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:14,017 - root - ERROR - ('512532', 'not_found')
2021-09-22 19:50:14,018 - root - ERROR - list index out of range
2021-09-22 19:50:14,019 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:15,140 - root - ERROR - ('512533', 'not_found')
2021-09-22 19:50:15,141 - root - ERROR - list index out of range
2021-09-22 19:50:15,142 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:15,964 - root - ERROR - ('512534', 'not_found')
2021-09-22 19:50:15,964 - root - ERROR - list index out of range
2021-09-22 19:50:15,965 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:16,675 - root - ERROR - ('512535', 'not_found')
2021-09-22 19:50:16,675 - root - ERROR - list index out of range
2021-09-22 19:50:16,675 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:17,498 - root - ERROR - ('512901', 'not_found')
2021-09-22 19:50:17,499 - root - ERROR - list index out of range
2021-09-22 19:50:17,500 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:18,313 - root - ERROR - ('512902', 'not_found')
2021-09-22 19:50:18,314 - root - ERROR - list index out of range
2021-09-22 19:50:18,314 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:19,393 - root - ERROR - ('512903', 'not_found')
2021-09-22 19:50:19,393 - root - ERROR - list index out of range
2021-09-22 19:50:19,394 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:20,263 - root - ERROR - ('512921', 'not_found')
2021-09-22 19:50:20,263 - root - ERROR - list index out of range
2021-09-22 19:50:20,264 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:20,980 - root - ERROR - ('512922', 'not_found')
2021-09-22 19:50:20,980 - root - ERROR - list index out of range
2021-09-22 19:50:20,981 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:21,698 - root - ERROR - ('512923', 'not_found')
2021-09-22 19:50:21,698 - root - ERROR - list index out of range
2021-09-22 19:50:21,699 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:22,415 - root - ERROR - ('512924', 'not_found')
2021-09-22 19:50:22,415 - root - ERROR - list index out of range
2021-09-22 19:50:22,416 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:23,235 - root - ERROR - ('512925', 'not_found')
2021-09-22 19:50:23,235 - root - ERROR - list index out of range
2021-09-22 19:50:23,236 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:23,949 - root - ERROR - ('512926', 'not_found')
2021-09-22 19:50:23,950 - root - ERROR - list index out of range
2021-09-22 19:50:23,950 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

2021-09-22 19:50:25,075 - root - ERROR - ('512927', 'not_found')
2021-09-22 19:50:25,076 - root - ERROR - list index out of range
2021-09-22 19:50:25,076 - root - ERROR - Traceback (most recent call last):
  File "C:\Project\Python\scripts\pandas_test\9.18_3_2.py", line 258, in <module>
    area = root.xpath("//div[@class='mcon f14 noi']/h2[1]/text()")[0]
IndexError: list index out of range

